language: go

env:
  - GO111MODULE=on

install:
  - go mod tidy

script:
 - go run examples/00_test/ext/ext.go &
 - go test ./fsm ./clf -cover -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
